# Generated by Django 5.0 on 2024-08-16 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description for your account')),
                ('number', models.CharField(help_text='Insert your account number here', max_length=20)),
                ('balance', models.FloatField(default=8, help_text='Insert your inicial balance')),
                ('comer', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
